# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business')], default='Residential', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_cell_phone',
            field=models.CharField(default='630-806-4430', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_email',
            field=models.CharField(default='jsudlow@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_fax_phone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_first_name',
            field=models.CharField(default='Jonathan', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_home_phone',
            field=models.CharField(default='630-806-4430', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_nick_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_title',
            field=models.CharField(choices=[('Builder', 'Builder'), ('Buyer', 'Buyer'), ('Caretaker', 'Caretaker'), ('COO', 'COO'), ('Daughter', 'Daughter'), ('Husband', 'Husband'), ('Manager', 'Manager'), ('Owner', 'Owner'), ('President', 'President'), ('Realtor', 'Realtor'), ('Seller', 'Seller'), ('Son', 'Son'), ('Tenant', 'Tenant'), ('Trustee', 'Trustee'), ('Vice-President', 'Vice-President'), ('Wife', 'Wife')], default='Mr.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_work_ext',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='main_contact_work_phone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
