# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofy', '0002_auto_20170924_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='Aurora', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.CharField(default='A wonderful gentleman', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='mailing_address',
            field=models.CharField(default='2254 Innisbrook Ct.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sales_rep',
            field=models.CharField(default='Jon Sudlow', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(choices=[('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Wisconsin', 'Wisconsin')], default='Illinois', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='zipcode',
            field=models.CharField(default='60502', max_length=200),
            preserve_default=False,
        ),
    ]
