# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roofy', '0003_auto_20170924_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('sales_rep', models.CharField(choices=[('admin', 'admin'), ('jsudlow', 'jsudlow')], max_length=200)),
                ('site_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Wisconsin', 'Wisconsin')], max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('site_notes', models.CharField(max_length=200)),
                ('site_type', models.CharField(choices=[('4-Plex', '4-Plex'), ('Agriculture/Range', 'Agriculture/Ranch'), ('Apartment Building', 'Apartment Building'), ('Apartment Complex', 'Apartment Complex'), ('Cabin', 'Cabin'), ('Commercial - Gas Station', 'Commercial - Gas Station'), ('Commercial - Hotel', 'Commercial - Hotel'), ('Commercial - Other', 'Commercial - Other'), ('Commercial - Church', 'Commercial - Church'), ('Commercial - Retail', 'Commercial - Retail'), ('Duplex', 'Duplex'), ('Garages/Shed', 'Garages/Shed'), ('Gazebo', 'Gazebo'), ('New Construction', 'New Construction'), ('Residential-Own', 'Residential-Own'), ('Residential-Rental', 'Residential-Rental')], max_length=200)),
                ('lead_source', models.CharField(choices=[('Angies List', 'Angies List'), ('BBB', 'BBB'), ('Canvassing', 'Canvassing'), ('Direct Mail', 'Direct Mail'), ('Previous Customer', 'Previous Customer'), ('Referral', 'Referral'), ('Self Generated', 'Self Generated'), ('Telemarketing Campaign', 'Telemarketing Campaign'), ('Truck Decals', 'Truck Decals'), ('Website', 'Website'), ('Yard Sign', 'Yard Sign')], max_length=200)),
                ('refered_by', models.CharField(max_length=200)),
                ('storm_date', models.DateField()),
                ('claim_number', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=200)),
                ('insurance_company', models.CharField(max_length=200)),
                ('mortgage_company', models.CharField(max_length=200)),
                ('roof_style', models.CharField(choices=[('Flat Roof', 'Flat Roof'), ('Steel Roof', 'Steel Roof'), ('Wood Shake', 'Wood Shake'), ('3-Tab Shingles', '3-Tab Shingles'), ('Architectural Shingles', 'Architectural Shingles'), ('Organic Shingles', 'Organic Shingles'), ('Slate Roof', 'Slate Roof'), ('Clay Tile Roof', 'Clay Tile Roof')], max_length=200)),
                ('steep', models.BooleanField()),
                ('walk_on', models.BooleanField()),
                ('how_many_stories', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=200)),
                ('elevation', models.CharField(choices=[('Brick', 'Brick'), ('Asphalt', 'Asphalt'), ('Aluminum', 'Aluminum'), ('Vinyl', 'Vinyl'), ('Brick/Siding', 'Brick/Siding'), ('Hardwood', 'Hardwood')], max_length=200)),
                ('damage_on_roof', models.BooleanField()),
                ('damage_on_siding', models.BooleanField()),
                ('damage_on_gutters', models.BooleanField()),
                ('damage_on_downspouts', models.BooleanField()),
                ('damage_on_window_wraps', models.BooleanField()),
                ('damage_on_ac', models.BooleanField()),
                ('type_of_roof_damage', models.CharField(choices=[('Hail', 'Hail'), ('Hail+Mising Shingles', 'Hail+Missing Shingles'), ('Wind', 'Wind'), ('Wind+Missing Shingles', 'Wind+Missing Shingles'), ('Racoon', 'Racoon'), ('Racoon+Missing Shingles', 'Racoon+Missing Shingles'), ('Hail&Wind', 'Hail&Wind'), ('Hail&Wind+Missing Shingles', 'Hail&Wind+Missing Shingles')], max_length=200)),
                ('how_many_layers', models.CharField(max_length=200)),
                ('interior_damage', models.BooleanField()),
                ('place_of_interior_damage', models.CharField(max_length=200)),
                ('pets_we_should_be_aware_of', models.BooleanField()),
                ('locked_gate', models.BooleanField()),
                ('garage_attached', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='main_contact_prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_rep',
            field=models.CharField(choices=[('admin', 'admin'), ('jsudlow', 'jsudlow')], max_length=200),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roofy.Client'),
        ),
    ]
