# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofy', '0004_auto_20170925_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='main_contact_last_name',
            field=models.CharField(default='Sudlow', max_length=200),
            preserve_default=False,
        ),
    ]
