# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roofy', '0007_auto_20170925_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=200)),
                ('note_type', models.CharField(choices=[('General', 'General'), ('Alerts', 'Alerts'), ('Appointment', 'Appointment'), ('Bills/Expenses', 'Bills/Expenses'), ('Call - Inbound', 'Call - Inbound'), ('Call - Outbound', 'Call - Outbound'), ('Contract', 'Contract'), ('Customer Complaint', 'Customer Complaint'), ('Customer Compliment', 'Customer Compliment'), ('EagleView', 'EagleView'), ('Email - Inbound', 'Email - Inbound'), ('Email - Outbound', 'Email - Outbound'), ('Fax', 'Fax'), ('File/Photo', 'File/Photo'), ('Follow Up', 'Follow Up'), ('Invoices', 'Invoices'), ('Jet Stream', 'Jet Stream'), ('Job Progress Update', 'Job Progress Update'), ('Material Order', 'Material Order'), ('Other', 'Other'), ('Payment', 'Payment'), ('Payout', 'Payout'), ('Permit', 'Permit'), ('Proposal/Estimate', 'Proposal/Estimate'), ('Refunds', 'Refunds'), ('Task', 'Task'), ('Work Order', 'Work Order'), ('Workflow', 'Workflow')], max_length=200)),
                ('date', models.DateField()),
                ('note_text', models.TextField()),
                ('origin', models.CharField(choices=[('User', 'User'), ('System', 'System')], max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roofy.Project')),
            ],
        ),
    ]
