# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofy', '0008_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.CharField(choices=[('admin', 'admin'), ('jsudlow', 'jsudlow')], max_length=200),
        ),
    ]
