# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofy', '0009_auto_20171002_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Inspection/Demo', 'Inspection/Demo'), ('Estimate/Proposal', 'Estimate/Proposal'), ('Contract Signed', 'Contract Signed'), ('Pre-Production', 'Pre-Production'), ('Production', 'Production'), ('Post-Production', 'Post-Production'), ('Accounts Receivable', 'Accounts Receivable'), ('Closed Pending', 'Closed Pending'), ('Closed - Complete', 'Closed - Complete'), ('Cancelled', 'Cancelled')], default='Lead', max_length=200),
            preserve_default=False,
        ),
    ]
